#!bin/bash

chmod +x *

while true; do

clear

figlet "        Toolzy " | lolcat
echo -e " \033[1;32m [!]\033[0m \033[1;33m Choose An Option!\033[0m"   
echo ' '
echo ' '
echo ' '
echo ' '
echo ' '
echo -e " \033[1;33m [01]\033[0m \033[1;31m Install Termux Packages \033[0m"      
echo " "
echo -e " \033[1;33m [02]\033[0m \033[1;31m Install Git Packages\033[0m"      
echo ' '
echo -e " \033[1;33m [03]\033[0m \033[1;31m Exit Of Toolzy\033[0m"      
echo ' '
echo ' '
read -p "~/ToolZy $ " yn

case $yn in
        [1] ) echo -e "\033[1;31m Starting...\033[0m" ;
clear
          sleep 2
bash DONTELL
                break;; 
       [2] ) echo -e "\033[1;31m Starting...\033[0m" ;
   clear
   
  sleep 2

bash DONTELL2.sh

               break;;
        [3] ) echo -e " \033[1;32m Exiting...\033[0m"  ;
                exit;;
        * ) echo -e " \033[1;33m [!]\033[0m \033[5;30m Invalid Option \033[0m"
esac

sleep 3

clear

done
