#!bin/bash
pkg install python-pip -y -y -y -y -y -y

pkg install figlet -y -y

pip install lolcat

chmod +x *

while true; do

clear

figlet "        Toolzy " | lolcat
echo -e " \033[1;32m [!]\033[0m \033[1;33m Choose An Option!\033[0m"   
echo ' '
echo -e " \033[1;33m [?]\033[0m \033[1;31m Want install the program?(y/n)\033[0m"      
echo ' '
echo ' '
echo " "
echo -e "\033[1;31m By Ixz Modder\033[0m"      
echo ' '
echo -e "\033[1;31m ©Copyright Ixz Modder\033[0m"      
echo ' '
echo ' '
read -p "~/ToolZy $ " yn

case $yn in
        [yY] ) echo -e "\033[1;31m Starting...\033[0m" ;
clear
          sleep 2
echo -e " \033[1;32m Installing Requests...\033[0m"    

sleep 3

clear

pkg upgrade && pkg update

sleep 3

clear

echo -e " \033[1;32m Installing Figlet\033[0m"   

sleep 3

pkg install figlet -y

sleep 3

clear

echo -e " \033[1;32m Installing Lolcat\033[0m"   

pip install lolcat 

sleep 2

clear

sleep 2

echo -e "\033[1;31m Starting ToolZy\033[0m"      

sleep 2

bash requests
               break;;
        [nN] ) echo -e " \033[1;32m Exiting...\033[0m"  ;
                exit;;
        * ) echo -e " \033[1;33m [!]\033[0m \033[5;30m Invalid Option \033[0m"
esac

sleep 3

clear

done
